name: Gallery Buil and Deploy
  
on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: '6.0.300'
      - name: Restore packages
        run: dotnet restore
      - name: Create Production Build
        run: dotnet publish -c Release --no-restore
      - name: Push to Linode Cloud
        run: |
          echo "$ssh_key" > ~/ssh_key
          chmod 600 ~/ssh_key
          rsync -e "ssh -i ~/ssh_key -o StrictHostKeyChecking=no" -avzr ./GalleryConcept/bin/Release/net6.0/publish/* "$user"@"$target_ip":/var/gallery/app
          ssh -i ~/ssh_key "$user"@"$target_ip" 'dotnet /var/gallery/app/GalleryConcept.dll'
        env:
          ssh_key: ${{secrets.GHUB_ACTIONS_SSH}}
          user: ${{secrets.GHUB_ACTIONS_USER}}
          target_ip: ${{secrets.LINODE_IP}}